// project/src/App.tsx
import React, { useState } from 'react';
import { useAuth } from './hooks/useAuth';
import { useTheme } from './hooks/useTheme';
import { useLanguage } from './hooks/useLanguage';
import { useData } from './hooks/useData';
import LoginForm from './components/LoginForm';
import SignUpForm from './components/SignUpForm';
import Layout from './components/Layout';
import Dashboard from './components/Dashboard';
import DraftManager from './components/DraftManager';
import ContentManager from './components/ContentManager';
import ProductManager from './components/ProductManager';
import UserManager from './components/UserManager';
import Calendar from './components/Calendar';
import Performance from './components/Performance';

function App() {
  const { user, company, login, signUp, logout } = useAuth();
  const { theme, toggleTheme } = useTheme();
  const { language } = useLanguage();
  const {
    drafts,
    content,
    products,
    users,
    addDraft,
    updateDraft,
    deleteDraft,
    addContent,
    updateContent,
    deleteContent,
    addProduct,
    updateProduct,
    deleteProduct,
    addUser,
    updateUser,
    deleteUser,
    transformDraftToContent
  } = useData(company?.id);

  const [activeTab, setActiveTab] = useState('dashboard');
  const [showSignUp, setShowSignUp] = useState(false);

  // If not logged in, show login form
  if (!user || !company) {
    if (showSignUp) {
      return (
        <SignUpForm 
          onSignUp={signUp} 
          onBackToLogin={() => setShowSignUp(false)} 
        />
      );
    }
    return (
      <LoginForm 
        onLogin={login} 
        onShowSignUp={() => setShowSignUp(true)} 
      />
    );
  }

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return <Dashboard user={user} drafts={drafts} content={content} />;
      case 'drafts':
        return (
          <DraftManager
            user={user}
            drafts={drafts}
            users={users}
            onAddDraft={addDraft}
            onUpdateDraft={updateDraft}
            onDeleteDraft={deleteDraft}
          />
        );
      case 'content':
        return (
          <ContentManager
            user={user}
            content={content}
            products={products}
            users={users}
            drafts={drafts}
            onAddContent={addContent}
            onUpdateContent={updateContent}
            onDeleteContent={deleteContent}
            onTransformDraft={transformDraftToContent}
          />
        );
      case 'products':
        return (
          <ProductManager
            user={user}
            products={products}
            onAddProduct={addProduct}
            onUpdateProduct={updateProduct}
            onDeleteProduct={deleteProduct}
          />
        );
      case 'users':
        return (
          <UserManager
            user={user}
            users={users}
            onAddUser={addUser}
            onUpdateUser={updateUser}
            onDeleteUser={deleteUser}
          />
        );
      case 'calendar':
        return (
          <Calendar
            user={user}
            content={content}
            products={products}
            users={users}
          />
        );
      case 'performance':
        return (
          <Performance
            user={user}
            content={content}
            products={products}
            users={users}
          />
        );
      default:
        return <Dashboard user={user} drafts={drafts} content={content} />;
    }
  };

  return (
    <Layout
      user={user}
      company={company}
      onLogout={logout}
      theme={theme}
      onToggleTheme={toggleTheme}
      activeTab={activeTab}
      onTabChange={setActiveTab}
    >
      {renderContent()}
    </Layout>
  );
}

export default App;

// src/App.vue
<template>
  <div>
    <!-- Login/SignUp Forms -->
    <SignUpForm 
      v-if="!user && !company && showSignUp"
      @signUp="signUp" 
      @backToLogin="showSignUp = false" 
    />
    <LoginForm 
      v-else-if="!user || !company"
      @login="login" 
      @showSignUp="showSignUp = true" 
    />
    
    <!-- Main Application -->
    <Layout
      v-else
      :user="user"
      :company="company"
      :theme="theme"
      :activeTab="activeTab"
      @logout="logout"
      @toggleTheme="toggleTheme"
      @tabChange="setActiveTab"
    >
      <component :is="currentComponent" v-bind="componentProps" />
    </Layout>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import { useAuth } from './composables/useAuth.js';
import { useTheme } from './composables/useTheme.js';
import { useData } from './composables/useData.js';
import LoginForm from './components/LoginForm.vue';
import SignUpForm from './components/SignUpForm.vue';
import Layout from './components/Layout.vue';
import Dashboard from './components/Dashboard.vue';
import DraftManager from './components/DraftManager.vue';
import ContentManager from './components/ContentManager.vue';
import ProductManager from './components/ProductManager.vue';
import UserManager from './components/UserManager.vue';
import Calendar from './components/Calendar.vue';
import Performance from './components/Performance.vue';

const { user, company, login, signUp, logout } = useAuth();
const { theme, toggleTheme } = useTheme();
const {
  drafts,
  content,
  products,
  users,
  addDraft,
  updateDraft,
  deleteDraft,
  addContent,
  updateContent,
  deleteContent,
  addProduct,
  updateProduct,
  deleteProduct,
  addUser,
  updateUser,
  deleteUser,
  transformDraftToContent
} = useData(computed(() => company.value?.id));

const activeTab = ref('dashboard');
const showSignUp = ref(false);

const setActiveTab = (tab: string) => {
  activeTab.value = tab;
};

const currentComponent = computed(() => {
  switch (activeTab.value) {
    case 'dashboard':
      return Dashboard;
    case 'drafts':
      return DraftManager;
    case 'content':
      return ContentManager;
    case 'products':
      return ProductManager;
    case 'users':
      return UserManager;
    case 'calendar':
      return Calendar;
    case 'performance':
      return Performance;
    default:
      return Dashboard;
  }
});

const componentProps = computed(() => {
  const baseProps = {
    user: user.value,
    drafts: drafts.value,
    content: content.value,
    products: products.value,
    users: users.value
  };

  switch (activeTab.value) {
    case 'drafts':
      return {
        ...baseProps,
        onAddDraft: addDraft,
        onUpdateDraft: updateDraft,
        onDeleteDraft: deleteDraft
      };
    case 'content':
      return {
        ...baseProps,
        onAddContent: addContent,
        onUpdateContent: updateContent,
        onDeleteContent: deleteContent,
        onTransformDraft: transformDraftToContent
      };
    case 'products':
      return {
        ...baseProps,
        onAddProduct: addProduct,
        onUpdateProduct: updateProduct,
        onDeleteProduct: deleteProduct
      };
    case 'users':
      return {
        ...baseProps,
        onAddUser: addUser,
        onUpdateUser: updateUser,
        onDeleteUser: deleteUser
      };
    default:
      return baseProps;
  }
});
</script>
